basePath: /
definitions:
  terraform.Change:
    properties:
      actions:
        description: Actions is a list of actions to be taken on the resource.
        items:
          type: string
        type: array
    type: object
  terraform.Plan:
    properties:
      resource_changes:
        description: ResourceChanges is a list of resource changes in the plan.
        items:
          $ref: '#/definitions/terraform.ResourceChange'
        type: array
    type: object
  terraform.ResourceChange:
    properties:
      address:
        description: Address is the address of the resource.
        type: string
      after:
        additionalProperties: true
        description: After is the state of the resource after the change.
        type: object
      before:
        additionalProperties: true
        description: Before is the state of the resource before the change.
        type: object
      change:
        allOf:
        - $ref: '#/definitions/terraform.Change'
        description: Change represents the actions to be taken on a resource.
      type:
        description: Type is the type of the resource.
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the API for the CloudCostGuard backend service.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: CloudCostGuard API
  version: "1.0"
paths:
  /estimate:
    post:
      consumes:
      - application/json
      description: Parses a Terraform plan, estimates the cost, and returns the estimated
        monthly cost.
      parameters:
      - description: Terraform Plan
        in: body
        name: plan
        required: true
        schema:
          $ref: '#/definitions/terraform.Plan'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              format: float64
              type: number
            type: object
        "400":
          description: Failed to parse Terraform plan
          schema:
            type: string
        "500":
          description: Failed to estimate cost
          schema:
            type: string
        "503":
          description: Pricing data is not yet available
          schema:
            type: string
      summary: Estimate Terraform plan cost
swagger: "2.0"
