name: CloudCostGuard CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Build
        run: go build -v ./...

  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Run unit tests
        run: go test -tags=unit ./...

  integration-test:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Run integration tests
        run: go test -tags=integration ./...

  e2e-test:
    name: Run End-to-End Tests
    runs-on: ubuntu-latest
    needs: [build, unit-test, integration-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run e2e tests
        run: docker-compose -f docker-compose.e2e.yml up --build --abort-on-container-exit
