name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -v -o cloudcostguard ./cmd/cloudcostguard

    - name: Run E2E Tests
      run: docker-compose -f docker-compose.e2e.yml up --build --exit-code-from cli-tester
